INSERT INTO filings (id, idFood, name, price) VALUES
                                                  (1, 1, 'Queijo', 2.50),
                                                  (2, 1, 'Presunto', 3.00),
                                                  (3, 1, 'Carne de sol', 5.00),
                                                  (4, 1, 'Frango', 4.00),
                                                  (5, 1, 'Coco', 1.50),
                                                  (6, 1, 'Chocolate', 2.00),
                                                  (7, 1, 'Banana', 2.00),
                                                  (8, 1, 'Leite condensado', 2.50),
                                                  (9, 1, 'Peito de peru', 3.50),
                                                  (10, 1, 'Tomate e orégano', 2.00),
                                                  (11, 1, 'Queijo coalho', 4.00),
                                                  (12, 1, 'Camarão', 7.00),
                                                  (13, 1, 'Alho-poró', 2.50),
                                                  (14, 1, 'Requeijão', 2.00),
                                                  (15, 1, 'Mussarela', 3.00);
INSERT INTO filings (id, idFood, name, price) VALUES
                                                  (1, 2, 'Queijo', 2.50),
                                                  (2, 2, 'Presunto', 3.00),
                                                  (3, 2, 'Carne de sol', 5.00),
                                                  (4, 2, 'Frango', 4.00),
                                                  (5, 2, 'Coco', 1.50),
                                                  (6, 2, 'Chocolate', 2.00),
                                                  (7, 2, 'Banana', 2.00),
                                                  (8, 2, 'Leite condensado', 2.50),
                                                  (9, 2, 'Peito de peru', 3.50),
                                                  (10, 2, 'Tomate e orégano', 2.00),
                                                  (11, 2, 'Queijo coalho', 4.00),
                                                  (12, 2, 'Camarão', 7.00),
                                                  (13, 2, 'Alho-poró', 2.50),
                                                  (14, 2, 'Requeijão', 2.00),
                                                  (15, 2, 'Mussarela', 3.00);
INSERT INTO filings (id, idFood, name, price) VALUES
                                                  (1, 3, 'Queijo', 2.50),
                                                  (2, 3, 'Presunto', 3.00),
                                                  (3, 3, 'Carne de sol', 5.00),
                                                  (4, 3, 'Frango', 4.00),
                                                  (5, 3, 'Coco', 1.50),
                                                  (6, 3, 'Chocolate', 2.00),
                                                  (7, 3, 'Banana', 2.00),
                                                  (8, 3, 'Leite condensado', 2.50),
                                                  (9, 3, 'Peito de peru', 3.50),
                                                  (10, 3, 'Tomate e orégano', 2.00),
                                                  (11, 3, 'Queijo coalho', 4.00),
                                                  (12, 3, 'Camarão', 7.00),
                                                  (13, 3, 'Alho-poró', 2.50),
                                                  (14, 3, 'Requeijão', 2.00),
                                                  (15, 3, 'Mussarela', 3.00);